# This file contains values from Cookiecutter

default_context:
  project_name: "fembots"
  project_description: "Fembots is a python command line tool which allows organiztaions to provide several features over non web browser or app interfaces."
  organization: "fembots"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "fembots"
  email: "masterlukeskywalker02@gmail.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
